name: Deploy Preview Build

on:
  push:
    branches: [ preview ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            fshstk/trommelbot:${{ github.sha }}
            fshstk/trommelbot:preview
          cache-from: type=registry,ref=fshstk/trommelbot:preview
          cache-to: type=inline

      - name: Deploy bot to trommelkreis.club
        uses: appleboy/ssh-action@master
        with:
          host: trommelkreis.club
          username: ${{ secrets.DOKKU_USERNAME }}
          key: ${{ secrets.DOKKU_PRIVATE_KEY }}
          script: dokku git:from-image trommelbot-dev fshstk/trommelbot:${{github.sha }}
